version: "3"

services:
  api:
    build: ../api
    ports:
      - "3000:3000"

  worker:
    build: ../worker

  redis:
    image: redis:7-alpine

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password

  ai:
    build: ../ai
