#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT_DIR}/.env.enterprise"
K8S_OUT_DIR="${ROOT_DIR}/k8s/generated"

log() {
  printf '[codex] %s\n' "$*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "Missing required command: $1"
    exit 1
  fi
}

rand_secret() {
  openssl rand -hex 24
}

clone_if_requested() {
  local repo_url="${1:-}"
  if [[ -z "$repo_url" ]]; then
    return
  fi

  require_cmd git
  local clone_dir="${ROOT_DIR}/external-src"
  log "Cloning ${repo_url} into ${clone_dir}"
  rm -rf "$clone_dir"
  git clone "$repo_url" "$clone_dir"
}

create_env_file() {
  log "Creating ${ENV_FILE}"

  local jwt_secret stripe_secret stripe_webhook ws_url
  jwt_secret="$(rand_secret)"
  stripe_secret="${STRIPE_SECRET_KEY:-sk_test_replace_me}"
  stripe_webhook="${STRIPE_WEBHOOK_SECRET:-whsec_replace_me}"
  ws_url="${LIVE_WS_URL:-wss://api.zeaz.dev/live}"

  cat > "$ENV_FILE" <<ENV
# Generated by codex.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Copy values into .env before production launch.
DB_PASS=$(rand_secret)
REDIS_PASS=$(rand_secret)
KAFKA_USER=zlinebot
KAFKA_PASS=$(rand_secret)
JWT_SECRET=${jwt_secret}
JWT_EXPIRES_IN=7d
STRIPE_SECRET_KEY=${stripe_secret}
STRIPE_WEBHOOK_SECRET=${stripe_webhook}
STRIPE_PRICE_ID=price_replace_me
LIVE_WS_URL=${ws_url}
MARKETPLACE_FEE_PERCENT=15
AFFILIATE_SIGNUP_CREDIT=10
APP_HOST=app.zlinebot-automos.local
API_HOST=api.zlinebot-automos.local
ENV
}

ensure_services() {
  require_cmd docker
  require_cmd docker compose

  log "Starting PostgreSQL + Redis + API + Worker baseline services"
  docker compose --env-file "$ENV_FILE" up -d db redis kafka api worker
}

generate_k8s_templates() {
  mkdir -p "$K8S_OUT_DIR"
  log "Rendering Kubernetes templates into ${K8S_OUT_DIR}"

  cp "${ROOT_DIR}/k8s/enterprise-api-deployment.yaml" "${K8S_OUT_DIR}/api.yaml"
  cp "${ROOT_DIR}/k8s/worker-deployment.yaml" "${K8S_OUT_DIR}/worker.yaml"
  cp "${ROOT_DIR}/k8s/enterprise-hpa.yaml" "${K8S_OUT_DIR}/hpa.yaml"
  cp "${ROOT_DIR}/k8s/postgres.yaml" "${K8S_OUT_DIR}/postgres.yaml"
  cp "${ROOT_DIR}/k8s/redis.yaml" "${K8S_OUT_DIR}/redis.yaml"
}

print_next_steps() {
  cat <<MSG

✅ Enterprise bootstrap complete.

Next steps:
1) Copy .env.enterprise into .env and replace placeholder keys (Stripe/JWT/WebSocket host).
2) Run database migrations and seed marketplace/referral tables.
3) Expose /market and /affiliate APIs behind auth middleware.
4) Deploy generated Kubernetes manifests from k8s/generated.
5) Add mobile client with JWT login + WebSocket feed.

Helpful commands:
  cp .env.enterprise .env
  docker compose --env-file .env.enterprise ps
  docker compose --env-file .env.enterprise logs -f api
MSG
}

usage() {
  cat <<HELP
Usage: bash codex.sh [options]

Options:
  --clone <repo-url>       Clone a source repo into ./external-src before bootstrap.
  --skip-docker            Skip docker compose startup (env + k8s generation only).
  -h, --help               Show help.
HELP
}

main() {
  local clone_url=""
  local skip_docker="false"

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --clone)
        clone_url="${2:-}"
        shift 2
        ;;
      --skip-docker)
        skip_docker="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        log "Unknown argument: $1"
        usage
        exit 1
        ;;
    esac
  done

  require_cmd openssl
  clone_if_requested "$clone_url"
  create_env_file
  generate_k8s_templates

  if [[ "$skip_docker" == "false" ]]; then
    ensure_services
  else
    log "Skipping docker startup by request"
  fi

  print_next_steps
}

main "$@"
