apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zlinebot-ingress
  namespace: zlinebot
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    external-dns.alpha.kubernetes.io/hostname: "bot.zeaz.dev,dashboard.zeaz.dev"
spec:
  tls:
    - hosts:
        - bot.zeaz.dev
        - dashboard.zeaz.dev
      secretName: zeaz-dev-tls
  rules:
    - host: bot.zeaz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
    - host: dashboard.zeaz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard-service
                port:
                  number: 80
