apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zlinebot-automos-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.zeaz.dev
        - api.zeaz.dev
      secretName: zeaz-dev-tls
  rules:
    - host: app.zeaz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zlinebot-automos-frontend
                port:
                  number: 80
    - host: api.zeaz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zlinebot-automos-api
                port:
                  number: 8000
