apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlinebot-automos-postgres
spec:
  selector:
    matchLabels:
      app: zlinebot-automos-postgres
  template:
    metadata:
      labels:
        app: zlinebot-automos-postgres
    spec:
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
      containers:
        - name: postgres
          image: postgres:16.4@sha256:3333333333333333333333333333333333333333333333333333333333333333
          env:
            - name: POSTGRES_DB
              value: zlinebot_automos
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zlinebot-automos-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zlinebot-automos-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 999
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: zlinebot-automos-postgres
  ports:
    - port: 5432
      targetPort: 5432
