apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlinebot-scheduler
  namespace: zlinebot
  labels:
    app: scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: zlinebot-scheduler-sa
      automountServiceAccountToken: false
      containers:
        - name: scheduler
          image: zeaz/zlinebot-scheduler:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: zlinebot-config
            - secretRef:
                name: bot-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
