apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeaz-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - zeaz.yourdomain.com
      secretName: zeaz-tls
  rules:
    - host: zeaz.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zeaz-api
                port:
                  number: 8000
