tunnel: __TUNNEL_ID__
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: __APP_HOST__
    service: https://nginx:443
    originRequest:
      noTLSVerify: true
  - hostname: __API_HOST__
    service: https://nginx:443
    originRequest:
      noTLSVerify: true
  - service: http_status:404
