tunnel: __TUNNEL_ID__
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: '*.zlinebot-automos.local'
    service: https://nginx:443
    originRequest:
      noTLSVerify: true
  - hostname: api.zlinebot-automos.local
    service: https://nginx:443
    originRequest:
      noTLSVerify: true
  - service: http_status:404
